<div style="text-align: center;">
  <img src="https://github.com/Hack-io-Data/Imagenes/blob/main/01-LogosHackio/logo_naranja@4x.png?raw=true" alt="esquema" />
</div>

In [1]:
import os

In [4]:
datos = os.listdir()
datos

['laboratorio-modulo2-leccion01-numpy.ipynb',
 'laboratorio-modulo2-leccion05-limpieza.ipynb',
 'laboratorio-modulo2-leccion04-visualizacion.ipynb',
 'laboratorio-modulo2-leccion03-groupby.ipynb',
 'laboratorio-modulo2-leccion02-eda-union.ipynb',
 'laboratorio-modulo2-leccion03-filtrado.ipynb']

In [ ]:
diccioanrio_df = {diccioanrio_df[re.findall("\d{4}", i)[0]] : pd.read_csv(f"..dato/{i}") for i in datos}

diccioanrio_df = {}
for i in datos:
    df = pd.read_csv(i)
    diccioanrio_df[i.spl]


for i in datos
# Laboratorio de NumPy

#### Ejercicio 1 - Crea un array de 1D con los números del 0 al 9.

In [1]:

import numpy as np

lista = [0,1,2,3,4,5,6,7,8,9]
array_uni = np.array (lista)
array_uni


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Ejercicio 2 - Convierte un array 1D en un array 2D con 2 filas y 5 columnas.

In [7]:
array_bi = np.reshape (array_uni, [2,5])
array_bi

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#### Ejercicio 3 - Encuentra los índices de los elementos con valor distinto de 0 en el siguiente array: [0, 2, 0, 3, 0, 4, 0].

In [18]:
array1 = np.array ([0,2,0,3,0,4,0])
mascara =  array1 != 0
mascara
distinto0 = array1 [mascara]
distinto0
indices_distinto0 = np.where (mascara)[0]
indices_distinto0


array([1, 3, 5])

#### Ejercicio 4 - Crea un array 3x3 con valores aleatorios entre 0 y 1.

In [21]:
array_aleatorio = np.random.rand(3,3)
array_aleatorio

array([[0.69182812, 0.22058302, 0.13500741],
       [0.31794679, 0.16029574, 0.50270916],
       [0.19548186, 0.78908091, 0.1596978 ]])

#### Ejercicio 5 - Crea un array de 10 números aleatorios y encuentra el valor máximo y mínimo.

In [10]:
array_10num = np.random.randint (0,10,10)
print (f"{array_10num}")
max_valor = np.max (array_10num)
print (f"el valor maximo es {max_valor}")
min_valor = np.min (array_10num)
print (f"el valor minimo es {min_valor}")

[6 6 7 4 6 0 0 2 5 1]
el valor maximo es 7
el valor minimo es 0


#### Ejercicio 6 - Crea un array de una dimensión e inviértelo. 

In [23]:
array_original = np.random.rand (5)
print(f"el array original es: {array_original}")
array_invertido = array_original [::-1]
print(f"el array invertidol es: {array_invertido}")


el array original es: [0.76817703 0.91670695 0.69889651 0.32237962 0.52444165]
el array invertidol es: [0.52444165 0.32237962 0.69889651 0.91670695 0.76817703]



#### Ejercicio 6 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Selecciona el primer `15` del array.

- Selecciona todos los elementos del primer array. 

- Selecciona la última fila del último array


In [ ]:
array_tri = np.random.randint (0,25,(2,3,4))
print (f"El array tridimensional es: \n {array_tri}")
primer15 = np.where (array_tri == 15)

print (f" el primer numero 15 está en la posicion {primer15}")




El array tridimensional es: 
 [[[19  3  5 10]
  [ 1 20 20 18]
  [23 14 15  8]]

 [[21 23  6  0]
  [ 9 16 12 14]
  [ 7 19 18 18]]]
 el primer numero 15 está en la posicion (array([0]), array([2]), array([2]))


In [25]:
array_tri [0]

array([[19,  3,  5, 10],
       [ 1, 20, 20, 18],
       [23, 14, 15,  8]], dtype=int32)

In [ ]:
array_tri [1,2]


array([ 7, 19, 18, 18], dtype=int32)


#### Ejercicio 7 - Genera un array tridimensional de dimensiones (3, 2, 5) con valores enteros del 1 al 30.

- Selecciona el subarray que contiene los dos primeros elementos de cada fila del primer array.

- Selecciona el subarray que contiene todas las filas de los dos últimos arrays.


In [31]:
array_tridimensional = np.random.randint (1,31, (3,2,5))
print (f"El array tridimensional es: \n {array_tridimensional}")


El array tridimensional es: 
 [[[19 17  7  8 27]
  [25 28  3  7  5]]

 [[ 6 21  8 10 25]
  [26 28 20  1 20]]

 [[ 6 15 21  2 25]
  [10  5 26  3  6]]]


In [33]:
array_tridimensional [0,:,:2]

array([[19, 17],
       [25, 28]], dtype=int32)

In [37]:
array_tridimensional [1:,:,:]

array([[[ 6, 21,  8, 10, 25],
        [26, 28, 20,  1, 20]],

       [[ 6, 15, 21,  2, 25],
        [10,  5, 26,  3,  6]]], dtype=int32)

#### Ejercicio 8 - Genera un array tridimensional de dimensiones (4, 3, 2) con valores enteros del 1 al 24.

- Cambia todos los elementos de la segunda fila del segundo array por `0`.

- Cambia todos los valores del último array a `-1`.


In [39]:
array_tridimensional2 = np.random.randint (1,25,(4,3,2))
print (f"El array tridimensional es: \n {array_tridimensional2}")

El array tridimensional es: 
 [[[ 3 23]
  [24 11]
  [24  3]]

 [[ 2 19]
  [ 7 24]
  [ 1  1]]

 [[ 6 15]
  [22  2]
  [ 8 21]]

 [[22 19]
  [18 23]
  [21 17]]]


In [40]:
array_tridimensional2 [1,1,:] = 0
print (f"El array tridimensional es: \n {array_tridimensional2}")

El array tridimensional es: 
 [[[ 3 23]
  [24 11]
  [24  3]]

 [[ 2 19]
  [ 0  0]
  [ 1  1]]

 [[ 6 15]
  [22  2]
  [ 8 21]]

 [[22 19]
  [18 23]
  [21 17]]]


In [42]:
array_tridimensional2 [-1,:,:] = -1
print (f"El array tridimensional es: \n {array_tridimensional2}")

El array tridimensional es: 
 [[[ 3 23]
  [24 11]
  [24  3]]

 [[ 2 19]
  [ 0  0]
  [ 1  1]]

 [[ 6 15]
  [22  2]
  [ 8 21]]

 [[-1 -1]
  [-1 -1]
  [-1 -1]]]



#### Ejercicio 9 - Genera un array tridimensional de dimensiones (2, 4, 3) con valores enteros del -10 al 13.

- Selecciona todos los elementos mayores a `5`.

- Reemplaza todos los elementos negativos por `0`.


In [51]:
array_tridimensional3 = np.random.randint (-10,14, (2,4,3))
print (f"El array tridimensional es: \n {array_tridimensional3}")

El array tridimensional es: 
 [[[-9 -5  2]
  [-1  2 12]
  [ 5  1 -1]
  [12  2 13]]

 [[ 2 -5  0]
  [-4  8 -2]
  [ 6  3  0]
  [-4 12  9]]]


In [53]:
mascara2 = array_tridimensional3 > 5
array_mayor5 = array_tridimensional3 [mascara2]
print (f"El array tridimensional es: \n {array_mayor5}")

El array tridimensional es: 
 [12 12 13  8  6 12  9]


In [60]:
mascara3 =array_tridimensional3 <0
print(f"{mascara3}")
array_tridimensional3 [mascara3] = 0

print (f"El array tridimensional es: \n {array_tridimensional3}")
        


[[[ True  True False]
  [ True False False]
  [False False  True]
  [False False False]]

 [[False  True False]
  [ True False  True]
  [False False False]
  [ True False False]]]
El array tridimensional es: 
 [[[ 0  0  2]
  [ 0  2 12]
  [ 5  1  0]
  [12  2 13]]

 [[ 2  0  0]
  [ 0  8  0]
  [ 6  3  0]
  [ 0 12  9]]]


#### Ejercicio 10 - Genera un array tridimensional de dimensiones (3, 3, 3) con valores enteros del 1 al 27.

- Selecciona el subarray del segundo array que contenga solo las dos primeras columnas.

- Selecciona todos los elementos del tercer array que sean mayores que `20`.


In [71]:
array_tridimensional4 = np.random.randint (1,28, (3,3,3))
print (f"{array_tridimensional4}")

[[[ 5  4  2]
  [17 10 15]
  [ 3 13 12]]

 [[17 20 13]
  [ 6 20 14]
  [21 16 21]]

 [[15 24 13]
  [27  1  6]
  [ 8  8 18]]]


In [72]:
array_tridimensional4 [1,:,0:2]

array([[17, 20],
       [ 6, 20],
       [21, 16]], dtype=int32)

In [79]:
array_tridimensional4 = np.random.randint (1,28, (3,3,3))
print (f"{array_tridimensional4}")
array_tridimensional4_tercersub = array_tridimensional4 [2,:,:]
mascara4 = array_tridimensional4_tercersub > 20
array_mayor20 = array_tridimensional4_tercersub [mascara4]
print (f"\n los valores del tercer array mayores de 20 son: {array_mayor20}")


[[[24  3 15]
  [21 20 19]
  [25 22 20]]

 [[ 5  4 27]
  [15 17 11]
  [17 15 13]]

 [[19  5 21]
  [10 12 16]
  [16 26 26]]]

 los valores del tercer array mayores de 20 son: [21 26 26]


#### Ejercicio 11 - Crea un array de 10 números aleatorios y reemplaza los valores máximos y mínimos por 0.

In [103]:

array_aleatorio2 = np.random.rand (10)
print (f"{array_aleatorio2}")

valor_maximo = np.max (array_aleatorio2) 
valor_minimo = np.min (array_aleatorio2)

indice_maximo = np.where(array_aleatorio2 == valor_maximo)[0][0]
print (f"el valor maximo esta en el indice {indice_maximo}")
indice_minimo = np.where(array_aleatorio2 == valor_minimo)[0][0]
print (f"el valor minimo esta en el indice{indice_minimo}")

array_aleatorio2 [indice_maximo] = 0
array_aleatorio2 [indice_minimo] = 0
print(f"{array_aleatorio2}")


[0.31068649 0.50077002 0.93092504 0.67893246 0.67967423 0.85640123
 0.96828576 0.9496808  0.34965938 0.80823823]
el valor maximo esta en el indice 6
el valor minimo esta en el indice0
[0.         0.50077002 0.93092504 0.67893246 0.67967423 0.85640123
 0.         0.9496808  0.34965938 0.80823823]


#### Ejercicio 12 - Genera un array de 15 números aleatorios enteros entre 1 y 100 y reordénalo en orden ascendente.

In [109]:
array_aleatorio3 = np.random.randint (1,101,15)
print (f"{array_aleatorio3}")

array_aleatorio3_ordenado = np.sort(array_aleatorio3)
print (f"{array_aleatorio3_ordenado}")

[ 2 39 29 78  4 16 95 43 64 23 46 56 45 91 40]
[ 2  4 16 23 29 39 40 43 45 46 56 64 78 91 95]


#### Ejercicio 11 - Calcula la suma de los elementos a lo largo de las filas y columnas en una matriz 4x4.

In [119]:
array_aleatorio4 = np.random.rand (1,4,4)
print (f"{array_aleatorio4}\n")
sumafilas_array4 = np.sum (array_aleatorio4, axis = 1)
print (f" la suma de todos los elemento de las filas es \n {sumafilas_array4}\n")
sumacolumna_array4 = np.sum (array_aleatorio4, axis = 0)
print (f" la suma de todos los elemento de las columnas es \n {sumacolumna_array4}\n")

[[[0.30050512 0.36984443 0.30885293 0.1014852 ]
  [0.928012   0.57633035 0.06713821 0.55906497]
  [0.44781791 0.0978776  0.16395897 0.97874058]
  [0.87241923 0.30938789 0.83425781 0.8786769 ]]]

 la suma de todos los elemento de las filas es 
 [[2.54875426 1.35344028 1.37420792 2.51796765]]

 la suma de todos los elemento de las columnas es 
 [[0.30050512 0.36984443 0.30885293 0.1014852 ]
 [0.928012   0.57633035 0.06713821 0.55906497]
 [0.44781791 0.0978776  0.16395897 0.97874058]
 [0.87241923 0.30938789 0.83425781 0.8786769 ]]



#### Ejercicio 12 - Crea una matriz de 5x5 con valores en el borde igual a 1 y en el interior igual a 0.

#### Ejercicio 13 - Calcula la media y la desviación estándar de un array de 10 números aleatorios.

#### Ejercicio 14 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Transpón el array para intercambiar los ejes de la forma (2, 3, 4) a (4, 3, 2).

- Observa cómo cambian las posiciones de los elementos y sus índices después de la transposición. Explica en una celda de markdown que es lo que ha pasado. 


#### Ejercicio 15 - Genera un array tridimensional de dimensiones (3, 4, 2) con valores enteros del 1 al 24.

- Transpón el array para intercambiar el primer y segundo eje, de manera que la nueva forma del array sea (4, 3, 2).


#### Ejercicio 16 - Genera un array tridimensional de dimensiones (3, 2, 4) con valores enteros del 1 al 24.

- Realiza una rotación completa de los ejes para convertir la forma original (3, 2, 4) en (4, 3, 2).


#### Ejercicio 17 - Manipulación de Arrays en 3D

- Crea un array tridimensional con dimensiones (3, 4, 5) cuyos elementos sean números enteros aleatorios entre -10 y 10.

- Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Luego, reemplaza los valores de la matriz vacía basada en los valores del primer array bajo las siguientes condiciones:

   - Si el valor es igual a la mediana, se reemplaza por `"M"`.

   - Si el valor es mayor que la mediana, se reemplaza por `"X"`.

   - Si el valor es menor que la mediana, se reemplaza por `"Y"`.

   - Si el valor es igual al máximo, se reemplaza por `"MAX"`.

   - Si el valor es igual al mínimo, se reemplaza por `"MIN"`.


#### Ejercicio 18 - Verificación de Filas y Columnas Iguales

Crea un array bidimensional de dimensiones 4x4, escribe un código para determinar si alguna fila es exactamente igual a alguna columna.

**Reglas:**

- No puedes usar funciones predefinidas de NumPy para comparar filas y columnas (`np.array_equal`, etc.).

- Debes resolverlo con estructuras básicas de Python (bucles, condicionales, etc.).

- Debes revisar si hay al menos una fila que coincida exactamente con alguna columna.

**Pistas**:

- Puedes recorrer cada fila y cada columna de la matriz usando bucles.

- Para comparar una fila con una columna, puedes hacerlo elemento por elemento.