<div style="text-align: center;">
  <img src="https://github.com/Hack-io-Data/Imagenes/blob/main/01-LogosHackio/logo_naranja@4x.png?raw=true" alt="esquema" />
</div>

In [1]:
import os

In [2]:
datos = os.listdir()
datos

['laboratorio-modulo2-leccion01-numpy.ipynb']

In [3]:
diccioanrio_df = {diccioanrio_df[re.findall("\d{4}", i)[0]] : pd.read_csv(f"..dato/{i}") for i in datos}

diccioanrio_df = {}
for i in datos:
    df = pd.read_csv(i)
    diccioanrio_df[i.spl]


<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\Javier\AppData\Local\Temp\ipykernel_14820\1996085454.py:1: SyntaxWarning: invalid escape sequence '\d'
  diccioanrio_df = {diccioanrio_df[re.findall("\d{4}", i)[0]] : pd.read_csv(f"..dato/{i}") for i in datos}
C:\Users\Javier\AppData\Local\Temp\ipykernel_14820\1996085454.py:1: SyntaxWarning: invalid escape sequence '\d'
  diccioanrio_df = {diccioanrio_df[re.findall("\d{4}", i)[0]] : pd.read_csv(f"..dato/{i}") for i in datos}


NameError: name 'diccioanrio_df' is not defined

for i in datos
# Laboratorio de NumPy

#### Ejercicio 1 - Crea un array de 1D con los números del 0 al 9.

In [ ]:

import numpy as np

lista = [0,1,2,3,4,5,6,7,8,9]
array_uni = np.array (lista)
array_uni


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Ejercicio 2 - Convierte un array 1D en un array 2D con 2 filas y 5 columnas.

In [ ]:
array_bi = np.reshape (array_uni, [2,5])
array_bi

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#### Ejercicio 3 - Encuentra los índices de los elementos con valor distinto de 0 en el siguiente array: [0, 2, 0, 3, 0, 4, 0].

In [ ]:
array1 = np.array ([0,2,0,3,0,4,0])
mascara =  array1 != 0
mascara
distinto0 = array1 [mascara]
distinto0
indices_distinto0 = np.where (mascara)[0]
indices_distinto0


array([1, 3, 5])

#### Ejercicio 4 - Crea un array 3x3 con valores aleatorios entre 0 y 1.

In [ ]:
array_aleatorio = np.random.rand(3,3)
array_aleatorio

array([[0.50944292, 0.84418578, 0.72708099],
       [0.63389586, 0.35992269, 0.34619479],
       [0.02042388, 0.92449048, 0.87096468]])

#### Ejercicio 5 - Crea un array de 10 números aleatorios y encuentra el valor máximo y mínimo.

In [ ]:
array_10num = np.random.randint (0,10,10)
print (f"{array_10num}")
max_valor = np.max (array_10num)
print (f"el valor maximo es {max_valor}")
min_valor = np.min (array_10num)
print (f"el valor minimo es {min_valor}")

[6 7 8 0 1 4 5 1 1 8]
el valor maximo es 8
el valor minimo es 0


#### Ejercicio 6 - Crea un array de una dimensión e inviértelo. 

In [ ]:
array_original = np.random.rand (5)
print(f"el array original es: {array_original}")
array_invertido = array_original [::-1]
print(f"el array invertidol es: {array_invertido}")


el array original es: [0.93563464 0.21754954 0.44157565 0.98979298 0.58773193]
el array invertidol es: [0.58773193 0.98979298 0.44157565 0.21754954 0.93563464]



#### Ejercicio 6 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Selecciona el primer `15` del array.

- Selecciona todos los elementos del primer array. 

- Selecciona la última fila del último array


In [ ]:
array_tri = np.random.randint (0,25,(2,3,4))
print (f"El array tridimensional es: \n {array_tri}")
primer15 = np.where (array_tri == 15)

print (f" el primer numero 15 está en la posicion {primer15}")




El array tridimensional es: 
 [[[ 0 11 21  4]
  [ 0  4 24 23]
  [23 18 20 19]]

 [[14  3 24 21]
  [ 7  5  2  6]
  [ 0 11 18 24]]]
 el primer numero 15 está en la posicion (array([], dtype=int64), array([], dtype=int64), array([], dtype=int64))


In [ ]:
array_tri [0]

array([[ 0, 11, 21,  4],
       [ 0,  4, 24, 23],
       [23, 18, 20, 19]], dtype=int32)

In [ ]:
array_tri [1,2]


array([ 0, 11, 18, 24], dtype=int32)


#### Ejercicio 7 - Genera un array tridimensional de dimensiones (3, 2, 5) con valores enteros del 1 al 30.

- Selecciona el subarray que contiene los dos primeros elementos de cada fila del primer array.

- Selecciona el subarray que contiene todas las filas de los dos últimos arrays.


In [ ]:
array_tridimensional = np.random.randint (1,31, (3,2,5))
print (f"El array tridimensional es: \n {array_tridimensional}")


El array tridimensional es: 
 [[[27 21  9  9 21]
  [ 4 10  6 12 11]]

 [[11 15  6 15  5]
  [14 11  3 21  2]]

 [[20  5 15 26 11]
  [ 6 10 13  1 15]]]


In [ ]:
array_tridimensional [0,:,:2]

array([[27, 21],
       [ 4, 10]], dtype=int32)

In [ ]:
array_tridimensional [1:,:,:]

array([[[11, 15,  6, 15,  5],
        [14, 11,  3, 21,  2]],

       [[20,  5, 15, 26, 11],
        [ 6, 10, 13,  1, 15]]], dtype=int32)

#### Ejercicio 8 - Genera un array tridimensional de dimensiones (4, 3, 2) con valores enteros del 1 al 24.

- Cambia todos los elementos de la segunda fila del segundo array por `0`.

- Cambia todos los valores del último array a `-1`.


In [ ]:
array_tridimensional2 = np.random.randint (1,25,(4,3,2))
print (f"El array tridimensional es: \n {array_tridimensional2}")

El array tridimensional es: 
 [[[ 6 11]
  [21 14]
  [11  1]]

 [[ 3 12]
  [20 21]
  [21 22]]

 [[ 9  1]
  [12 24]
  [ 3  4]]

 [[ 9  1]
  [ 4 12]
  [ 5 20]]]


In [ ]:
array_tridimensional2 [1,1,:] = 0
print (f"El array tridimensional es: \n {array_tridimensional2}")

El array tridimensional es: 
 [[[ 6 11]
  [21 14]
  [11  1]]

 [[ 3 12]
  [ 0  0]
  [21 22]]

 [[ 9  1]
  [12 24]
  [ 3  4]]

 [[ 9  1]
  [ 4 12]
  [ 5 20]]]


In [ ]:
array_tridimensional2 [-1,:,:] = -1
print (f"El array tridimensional es: \n {array_tridimensional2}")

El array tridimensional es: 
 [[[ 6 11]
  [21 14]
  [11  1]]

 [[ 3 12]
  [ 0  0]
  [21 22]]

 [[ 9  1]
  [12 24]
  [ 3  4]]

 [[-1 -1]
  [-1 -1]
  [-1 -1]]]



#### Ejercicio 9 - Genera un array tridimensional de dimensiones (2, 4, 3) con valores enteros del -10 al 13.

- Selecciona todos los elementos mayores a `5`.

- Reemplaza todos los elementos negativos por `0`.


In [ ]:
array_tridimensional3 = np.random.randint (-10,14, (2,4,3))
print (f"El array tridimensional es: \n {array_tridimensional3}")

El array tridimensional es: 
 [[[  8   2   1]
  [ -5   8   2]
  [ -9  -3  11]
  [ -7  12   0]]

 [[ -5   6  -2]
  [ -9 -10  13]
  [  6  -9  -8]
  [  4   9   9]]]


In [ ]:
mascara2 = array_tridimensional3 > 5
array_mayor5 = array_tridimensional3 [mascara2]
print (f"El array tridimensional es: \n {array_mayor5}")

El array tridimensional es: 
 [ 8  8 11 12  6 13  6  9  9]


In [ ]:
mascara3 =array_tridimensional3 <0
print(f"{mascara3}")
array_tridimensional3 [mascara3] = 0

print (f"El array tridimensional es: \n {array_tridimensional3}")
        


[[[False False False]
  [ True False False]
  [ True  True False]
  [ True False False]]

 [[ True False  True]
  [ True  True False]
  [False  True  True]
  [False False False]]]
El array tridimensional es: 
 [[[ 8  2  1]
  [ 0  8  2]
  [ 0  0 11]
  [ 0 12  0]]

 [[ 0  6  0]
  [ 0  0 13]
  [ 6  0  0]
  [ 4  9  9]]]


#### Ejercicio 10 - Genera un array tridimensional de dimensiones (3, 3, 3) con valores enteros del 1 al 27.

- Selecciona el subarray del segundo array que contenga solo las dos primeras columnas.

- Selecciona todos los elementos del tercer array que sean mayores que `20`.


In [ ]:
array_tridimensional4 = np.random.randint (1,28, (3,3,3))
print (f"{array_tridimensional4}")

[[[16 25 12]
  [15 23 13]
  [22 10 27]]

 [[25 11 18]
  [13  4 11]
  [ 7 27  8]]

 [[20 16 12]
  [15 20 26]
  [23 23 15]]]


In [ ]:
array_tridimensional4 [1,:,0:2]

array([[25, 11],
       [13,  4],
       [ 7, 27]], dtype=int32)

In [ ]:
array_tridimensional4 = np.random.randint (1,28, (3,3,3))
print (f"{array_tridimensional4}")
array_tridimensional4_tercersub = array_tridimensional4 [2,:,:]
mascara4 = array_tridimensional4_tercersub > 20
array_mayor20 = array_tridimensional4_tercersub [mascara4]
print (f"\n los valores del tercer array mayores de 20 son: {array_mayor20}")


[[[26  8 24]
  [16 18  6]
  [21  4  8]]

 [[17 25 10]
  [ 8 14 23]
  [23  3  9]]

 [[ 9  4  6]
  [27 13 25]
  [16 17  1]]]

 los valores del tercer array mayores de 20 son: [27 25]


#### Ejercicio 11 - Crea un array de 10 números aleatorios y reemplaza los valores máximos y mínimos por 0.

In [ ]:

array_aleatorio2 = np.random.rand (10)
print (f"{array_aleatorio2}")

valor_maximo = np.max (array_aleatorio2) 
valor_minimo = np.min (array_aleatorio2)

indice_maximo = np.where(array_aleatorio2 == valor_maximo)[0][0]
print (f"el valor maximo esta en el indice {indice_maximo}")
indice_minimo = np.where(array_aleatorio2 == valor_minimo)[0][0]
print (f"el valor minimo esta en el indice{indice_minimo}")

array_aleatorio2 [indice_maximo] = 0
array_aleatorio2 [indice_minimo] = 0
print(f"{array_aleatorio2}")


[0.65522381 0.71211625 0.89106113 0.28469646 0.56072142 0.69204429
 0.82832016 0.84335083 0.8329697  0.72159887]
el valor maximo esta en el indice 2
el valor minimo esta en el indice3
[0.65522381 0.71211625 0.         0.         0.56072142 0.69204429
 0.82832016 0.84335083 0.8329697  0.72159887]


#### Ejercicio 12 - Genera un array de 15 números aleatorios enteros entre 1 y 100 y reordénalo en orden ascendente.

In [ ]:
array_aleatorio3 = np.random.randint (1,101,15)
print (f"{array_aleatorio3}")

array_aleatorio3_ordenado = np.sort(array_aleatorio3)
print (f"{array_aleatorio3_ordenado}")

[ 8 95 34 91  2 78 84  7 44 51 18 70 10 90 95]
[ 2  7  8 10 18 34 44 51 70 78 84 90 91 95 95]


#### Ejercicio 11 - Calcula la suma de los elementos a lo largo de las filas y columnas en una matriz 4x4.

In [ ]:
array_aleatorio4 = np.random.rand (1,4,4)
print (f"{array_aleatorio4}\n")
sumafilas_array4 = np.sum (array_aleatorio4, axis = 1)
print (f" la suma de todos los elemento de las filas es \n {sumafilas_array4}\n")
sumacolumna_array4 = np.sum (array_aleatorio4, axis = 0)
print (f" la suma de todos los elemento de las columnas es \n {sumacolumna_array4}\n")

[[[0.73858188 0.78658734 0.61309142 0.34995286]
  [0.64722838 0.22426064 0.89113205 0.41026104]
  [0.20998641 0.93787096 0.65922632 0.35887902]
  [0.76806992 0.02715762 0.91140118 0.37783336]]]

 la suma de todos los elemento de las filas es 
 [[2.36386659 1.97587656 3.07485097 1.49692628]]

 la suma de todos los elemento de las columnas es 
 [[0.73858188 0.78658734 0.61309142 0.34995286]
 [0.64722838 0.22426064 0.89113205 0.41026104]
 [0.20998641 0.93787096 0.65922632 0.35887902]
 [0.76806992 0.02715762 0.91140118 0.37783336]]



#### Ejercicio 12 - Crea una matriz de 5x5 con valores en el borde igual a 1 y en el interior igual a 0.

In [ ]:
array_aleatorio5 = np.zeros ((5,5), dtype=int)
print (f"{array_aleatorio5}")
array_aleatorio5 [0,:] =1
array_aleatorio5 [:,0] = 1
array_aleatorio5 [:,-1] = 1
array_aleatorio5 [-1,:] = 1

print (f"{array_aleatorio5}")

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### Ejercicio 13 - Calcula la media y la desviación estándar de un array de 10 números aleatorios.

In [ ]:
array_aleatorio6 = np.random.rand (10)
print (f"{array_aleatorio6}")

[0.0604452  0.96363865 0.12671059 0.12265411 0.05073265 0.11032882
 0.03803101 0.4812346  0.63682302 0.01007587]


In [ ]:
array_media = np.mean(array_aleatorio6)
print (f"{array_media}")

0.2600674528328723


In [ ]:
array_desv = np.std(array_aleatorio6)
print (f"{array_desv}")

0.3066637110978543


#### Ejercicio 14 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Transpón el array para intercambiar los ejes de la forma (2, 3, 4) a (4, 3, 2).

- Observa cómo cambian las posiciones de los elementos y sus índices después de la transposición. Explica en una celda de markdown que es lo que ha pasado. 


In [ ]:
array_tridimensional5 = np.random.randint (1,25, (2,3,4))
print (f"{array_tridimensional5}")
array_transpuesto = np.transpose (array_tridimensional5, (2,1,0))
print (f"\n este es el array transpuesto \n {array_transpuesto}")

[[[18 11  1 23]
  [12 22 16  6]
  [17 21 10  5]]

 [[10 10 15  3]
  [ 9  1 11  9]
  [19  6  4 13]]]

 este es el array transpuesto 
 [[[18 10]
  [12  9]
  [17 19]]

 [[11 10]
  [22  1]
  [21  6]]

 [[ 1 15]
  [16 11]
  [10  4]]

 [[23  3]
  [ 6  9]
  [ 5 13]]]


### Ha cambiado el numero de columnas por el numero de arrays, el numero de arrays por el numero de columnas y las filas las ha dejado igual.

#### Ejercicio 15 - Genera un array tridimensional de dimensiones (3, 4, 2) con valores enteros del 1 al 24.

- Transpón el array para intercambiar el primer y segundo eje, de manera que la nueva forma del array sea (4, 3, 2).


In [ ]:
array_tridimensional6 = np.random.randint (1,25,(3,4,2))
print (f"{array_tridimensional6}")


[[[10  6]
  [22  5]
  [18 12]
  [24 16]]

 [[11 12]
  [ 5  6]
  [ 8 24]
  [ 5 11]]

 [[ 9 15]
  [13  5]
  [ 8  2]
  [14 16]]]


In [ ]:
array_transpuesto2 = np.transpose (array_tridimensional6, (1,0,2))
print (f"{array_transpuesto2}")

[[[10  6]
  [11 12]
  [ 9 15]]

 [[22  5]
  [ 5  6]
  [13  5]]

 [[18 12]
  [ 8 24]
  [ 8  2]]

 [[24 16]
  [ 5 11]
  [14 16]]]


#### Ejercicio 16 - Genera un array tridimensional de dimensiones (3, 2, 4) con valores enteros del 1 al 24.

- Realiza una rotación completa de los ejes para convertir la forma original (3, 2, 4) en (4, 3, 2).


In [ ]:
array_tridimensional7 = np.random.randint (1,24, (3,2,4), dtype=int)
print (f"{array_tridimensional7}")

[[[22 16 13 22]
  [ 3  2  5 17]]

 [[17 23 14 17]
  [11 19 22  5]]

 [[13  6 22  4]
  [ 9 22 17 23]]]


In [ ]:
array_transpuesto3 = np.transpose (array_tridimensional7, (2,0,1))
print (f"{array_transpuesto3}")

[[[22  3]
  [17 11]
  [13  9]]

 [[16  2]
  [23 19]
  [ 6 22]]

 [[13  5]
  [14 22]
  [22 17]]

 [[22 17]
  [17  5]
  [ 4 23]]]


#### Ejercicio 17 - Manipulación de Arrays en 3D

- Crea un array tridimensional con dimensiones (3, 4, 5) cuyos elementos sean números enteros aleatorios entre -10 y 10.

- Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Luego, reemplaza los valores de la matriz vacía basada en los valores del primer array bajo las siguientes condiciones:

   - Si el valor es igual a la mediana, se reemplaza por `"M"`.

   - Si el valor es mayor que la mediana, se reemplaza por `"X"`.

   - Si el valor es menor que la mediana, se reemplaza por `"Y"`.

   - Si el valor es igual al máximo, se reemplaza por `"MAX"`.

   - Si el valor es igual al mínimo, se reemplaza por `"MIN"`.


In [17]:
array_tridimensional8 = np.random.randint (-10,11,(3,4,5))
print (f"{array_tridimensional8}")

[[[  4   1  -6  -8  -8]
  [  7  -5   2  -6   8]
  [  9   8  -2   5   2]
  [ -9   9   5   6  -3]]

 [[ 10   1  -9   8  -2]
  [  3   7   6   0   6]
  [ 10   9   4   1  -3]
  [  0   1   1   3   9]]

 [[ -5   2   8   2  -2]
  [ 10  -9   2  -5   3]
  [ -4  -5  -1   4  -9]
  [  4 -10  -7   7  -8]]]


In [47]:
import numpy as np

array_vacio = np.empty ((3,4,5),dtype=object)
mediana = np.median (array_tridimensional8)
maximo = np.max(array_tridimensional8)
minimo = np.min (array_tridimensional8)

array_vacio [array_tridimensional8 == mediana] = "M"
array_vacio [array_tridimensional8 > mediana] = "X"
array_vacio [array_tridimensional8 < mediana] = "Y"
array_vacio [array_tridimensional8 == maximo] = "MAX"
array_vacio [array_tridimensional8 == minimo] = "MIN"

array_vacio


array([[['X', 'Y', 'Y', 'Y', 'Y'],
        ['X', 'Y', 'M', 'Y', 'X'],
        ['X', 'X', 'Y', 'X', 'M'],
        ['Y', 'X', 'X', 'X', 'Y']],

       [['MAX', 'Y', 'Y', 'X', 'Y'],
        ['X', 'X', 'X', 'Y', 'X'],
        ['MAX', 'X', 'X', 'Y', 'Y'],
        ['Y', 'Y', 'Y', 'X', 'X']],

       [['Y', 'M', 'X', 'M', 'Y'],
        ['MAX', 'Y', 'M', 'Y', 'X'],
        ['Y', 'Y', 'Y', 'X', 'Y'],
        ['X', 'MIN', 'Y', 'X', 'Y']]], dtype=object)

#### Ejercicio 18 - Verificación de Filas y Columnas Iguales

Crea un array bidimensional de dimensiones 4x4, escribe un código para determinar si alguna fila es exactamente igual a alguna columna.

**Reglas:**

- No puedes usar funciones predefinidas de NumPy para comparar filas y columnas (`np.array_equal`, etc.).

- Debes resolverlo con estructuras básicas de Python (bucles, condicionales, etc.).

- Debes revisar si hay al menos una fila que coincida exactamente con alguna columna.

**Pistas**:

- Puedes recorrer cada fila y cada columna de la matriz usando bucles.

- Para comparar una fila con una columna, puedes hacerlo elemento por elemento.

In [40]:
array_bidimensional8 = np.array ([[5,10,15,20],[100,200,300,400],[5,10,15,20],[101,200,300,400]])
array_bidimensional8


array([[  5,  10,  15,  20],
       [100, 200, 300, 400],
       [  5,  10,  15,  20],
       [101, 200, 300, 400]])

In [46]:
fila0 = array_bidimensional8 [0]
fila1 = array_bidimensional8 [1]
fila2 = array_bidimensional8 [2]
fila3 = array_bidimensional8 [3]

for i in fila0:
    for j in fila1:
        for k in fila2:
            for l in fila3:
                if i!=j or i!=k or i!=l:
                    print ("No hay filas iguales")
                elif i == j or i == k or i== l: 
                    print(f"Fila 0 tiene una fila igual")
                elif j == i or j == k or j == l: 
                    print(f"Fila 1 tiene una fila igual")
                elif k == i or k == j or k == l: 
                    print(f"Fila 2 tiene una fila igual")
                elif l == i or l == j or l == k: 
                    print(f"Fila 2 tiene una fila igual")
                else: print (f"No hay filas iguales")




No hay filas iguales
No hay filas iguales
No hay filas iguales
No hay filas iguales
No hay filas iguales
No hay filas iguales
No hay filas iguales
No hay filas iguales
No hay filas iguales
No hay filas iguales
No hay filas iguales
No hay filas iguales
No hay filas iguales
No hay filas iguales
No hay filas iguales
No hay filas iguales
No hay filas iguales
No hay filas iguales
No hay filas iguales
No hay filas iguales
No hay filas iguales
No hay filas iguales
No hay filas iguales
No hay filas iguales
No hay filas iguales
No hay filas iguales
No hay filas iguales
No hay filas iguales
No hay filas iguales
No hay filas iguales
No hay filas iguales
No hay filas iguales
No hay filas iguales
No hay filas iguales
No hay filas iguales
No hay filas iguales
No hay filas iguales
No hay filas iguales
No hay filas iguales
No hay filas iguales
No hay filas iguales
No hay filas iguales
No hay filas iguales
No hay filas iguales
No hay filas iguales
No hay filas iguales
No hay filas iguales
No hay filas 